using System;
namespace MeepLib.Messages.Exceptions
{
    /// <summary>
    /// An exception thrown by a pipeline module
    /// </summary>
    /// <remarks>This is how Meep does error handling in the pipeline itself, by treating them as just another Message
    /// type that can be filtered out, considered within or in parallel to the main pipeline.
    ///
    /// <para>Meep's &lt;Exceptions&gt; module will provide a feed of all ExceptionMessages generated by the pipeline,
    /// so you can log, store, analyse and forward them like any other Message.</para></remarks>
    public class ExceptionMessage : Message
    {
        public ExceptionMessage()
        { }

        public ExceptionMessage(string message)
        {
            this.Exception = new Exception(message);
        }

        public ExceptionMessage(Exception ex)
        {
            this.Exception = ex;
        }

        /// <summary>
        /// The DotNet Exception thrown
        /// </summary>
        public Exception Exception { get; set; }
    }
}
