using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MeepLib.Messages
{
    /// <summary>
    /// A single step in a sequence
    /// </summary>
    /// <remarks>These are generated by the Timer module, which increments
    /// Number by 1 on each event.</remarks>
    [DataContract]
    public class Step : StringMessage
    {
        /// <summary>
        /// Step number in a sequence
        /// </summary>
        /// <value>The number.</value>
        [DataMember, Index(IsUnique = false)] // Not unique because of restarts
        public long Number { get; set; }

        /// <summary>
        /// How long this step took to generate
        /// </summary>
        /// <value>The duration.</value>
        [DataMember, Index(IsUnique = false)]
        public TimeSpan Duration { get; set; } = TimeSpan.Zero;

        /// <summary>
        /// Last time a step was generated from the same source
        /// </summary>
        /// <value>The last issued.</value>
        [DataMember, Index(IsUnique = false)]
        public DateTime LastIssued { get; set; }
    }
}
